language: python
sudo: false
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO="Django>=1.8.0,<1.9.0"
  - DJANGO="Django>=1.10.0,<1.11.0"
  - DJANGO="Django>=1.11.0,<1.12.0"

# command to run tests
script:
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
after_success:
  - coveralls
